[en]
  title = "Coffee Brains"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[br]
  title = "Coffee Brains"
  languageName = "Português"
  languagedir = "ltr"
  contentdir = "content/br"
  weight = 2